name: push output

on:
  push:
    paths:
    - 'input/**.sld'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml -lib ./lib/
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        directory: 'Symbolenbibliotheken'
    # - name: setup git config
      # run:  |
        # git config user.name "KasperLingbeek"
        # git config user.email "<k.lingbeek@geonovum.nl>"
    # - name: Commit & Push changes
      # run: |
        # git add Symbolenbibliotheken/*.html
        # git commit -m "nieuwe html commit"
        # git push origin main
      
