name: push output

on:
  push:
    paths:
    - 'input/**.sld'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml -lib ./lib/

    # - name: Get repository
      # id: get_repository
      # uses: mavrosxristoforos/get-xml-info@1.0
      # with:
        # xml-file: 'temp/config.xml'
        # xpath: 'config/item[2]/github/repository'
    # - name: Create repository
      # run: curl -d '{"name":"${{ steps.get_repository.outputs.info }}","auto_init":true}' -u gwolbers:${{ secrets.USER_TOKEN }} https://api.github.com/user/repos
    # - name: Push output/respec
      # id: push_directory
      # uses: cpina/github-action-push-to-another-repository@main
      # env:
        # API_TOKEN_GITHUB: ${{ secrets.USER_TOKEN }}
      # with:
        # source-directory: ./output/respec/
        # destination-github-username: gwolbers
        # destination-repository-name: ${{ steps.get_repository.outputs.info }}
    # - name: Get server
      # id: get_server
      # uses: mavrosxristoforos/get-xml-info@1.0
      # with:
        # xml-file: 'temp/config.xml'
        # xpath: 'config/item[2]/ftp/server'
    # - name: Get username
      # id: get_username
      # uses: mavrosxristoforos/get-xml-info@1.0
      # with:
        # xml-file: 'temp/config.xml'
        # xpath: 'config/item[2]/ftp/username'
    # - name: Get currentVersion
      # id: get_currentVersion
      # uses: mavrosxristoforos/get-xml-info@1.0
      # with:
        # xml-file: 'temp/config.xml'
        # xpath: 'config/item[2]/ftp/currentVersion'
    # - name: Get lastPublishedVersion
      # id: get_lastPublishedVersion
      # uses: mavrosxristoforos/get-xml-info@1.0
      # with:
        # xml-file: 'temp/config.xml'
        # xpath: 'config/item[2]/ftp/lastPublishedVersion'
    # - name: Create currentVersion
      # uses: SamKirkland/FTP-Deploy-Action@4.2.0
      # with:
        # server: ${{ steps.get_server.outputs.info }}
        # username: ${{ steps.get_username.outputs.info }}
        # password: ${{ secrets.FTP_TOKEN }}
        # protocol: ftps
        # local-dir: ./output/snapshot/
        # server-dir: ${{ steps.get_currentVersion.outputs.info }}
# #       dry-run: true
    # - name: Create lastPublishedVersion
      # uses: SamKirkland/FTP-Deploy-Action@4.2.0
      # with:
        # server: ${{ steps.get_server.outputs.info }}
        # username: ${{ steps.get_username.outputs.info }}
        # password: ${{ secrets.FTP_TOKEN }}
        # protocol: ftps
        # local-dir: ./output/snapshot/
        # server-dir: ${{ steps.get_lastPublishedVersion.outputs.info }}
#       dry-run: true
